development:
  access_key_id: <%= ENV["aws_access_key_id"] %>
  secret_access_key: <%= ENV["aws_secret_access_key"] %>
  region: <%= ENV["aws_region"] %>
  bucket: <%= ENV["aws_s3_bucket"] %>
test:
  access_key_id: <%= ENV["aws_access_key_id"] %>
  secret_access_key: <%= ENV["aws_secret_access_key"] %>
  region: <%= ENV["aws_region"] %>
  bucket: <%= ENV["aws_s3_bucket"] %>
production:
  access_key_id: <%= ENV["aws_access_key_id"] %>
  secret_access_key: <%= ENV["aws_secret_access_key"] %>
  region: <%= ENV["aws_region"] %>
  bucket: <%= ENV["aws_s3_bucket"] %>
