default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: biz_db_development

test:
  <<: *default
  database: biz_db_test

production:
  <<: *default
  database: biz_db_production
